name: CI pipeline

on:
  push:
    branches:
      - "**" # matches every branch
      
jobs:
  lint:
    name: checkoutß
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Running isort.
        run: isort --check-only  .

      - name: Running flake8
        run: flake8 .
