name: S3 Deployment Test

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: PROD
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.0'

    - name: Install AWS CLI
      run: |
        pip install awscli
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: AKIAV6O4VTVTG4Q2PT7E
        aws-secret-access-key: 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
        aws-region: us-east-1

    - name: Upload Spark Code to S3
      run: |
        aws s3 cp etl/ s3://testing-cd-bucket-1/deployment/